openapi: 3.0.3
info:
  title: Imaging Study Appointment API
  version: 1.0.0
  description: API for managing imaging or lab session appointments.

servers:
  - url: http://localhost:8585

paths:
  /imagingStudy:
    post:
      summary: Create a new imaging or lab appointment
      operationId: createImagingStudy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentImaging'
      responses:
        "202":
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentImaging'
        "400":
          description: Invalid request payload
  /imagingStudy/{id}:
    get:
      summary: Get an imaging or lab appointment by ID
      operationId: getImagingStudyById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Appointment ID
      responses:
        "200":
          description: Appointment found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentImaging'
        "404":
          description: Appointment not found

components:
  schemas:
    AppointmentImaging:
      type: object
      required:
        - resourceType
        - status
        - start
        - end
        - patient
        - location
      properties:
        resourceType:
          type: string
          example: Appointment
        id:
          type: integer
          example: 1001
        status:
          type: string
          enum: [proposed, pending, booked, arrived, fulfilled, cancelled, noshow]
          example: booked
        appointmentType:
          type: string
          example: Imaging Session
        start:
          type: string
          format: date-time
          example: 2025-08-20T10:30:00Z
        end:
          type: string
          format: date-time
          example: 2025-08-20T11:00:00Z
        description:
          type: string
          example: MRI Brain Scan with contrast
        patient:
          $ref: '#/components/schemas/PatientReference'
        location:
          $ref: '#/components/schemas/LocationReference'
        practitioner:
          $ref: '#/components/schemas/PractitionerReference'
        serviceDetails:
          type: array
          items:
            $ref: '#/components/schemas/ServiceDetail'

    PatientReference:
      type: object
      required: [id, displayName]
      properties:
        id:
          type: string
          example: pat-2024
        displayName:
          type: string
          example: John Doe

    LocationReference:
      type: object
      required: [id, displayName]
      properties:
        id:
          type: string
          example: loc-001
        displayName:
          type: string
          example: Radiology Department - Main Hospital

    PractitionerReference:
      type: object
      properties:
        id:
          type: string
          example: prac-451
        displayName:
          type: string
          example: Dr. Sarah Wilson

    ServiceDetail:
      type: object
      required: [code]
      properties:
        code:
          type: string
          example: MRI
        description:
          type: string
          example: Magnetic Resonance Imaging - Brain
