[package]
org = "wso2"
name = "appointment_booking_template"
version = "0.1.0"
distribution = "2201.12.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2healthcare"
name = "imaging.service.client"
version="0.1.0"
