[package]
org = "wso2"
name = "imaging_client_service"
version = "1.0.0"
distribution = "2201.12.7"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "r4", "ImagingStudy", "health.fhir.r4.international401"]
template = true
